config/routes.rb
Rails.application.routes.draw do
  
  resources :cartridge_transfers
  resources :cartridge_supplies
  resources :cartridges
  get 'checklist/index'

  get 'checklist/new'

  resources :day_road_lists

  
  get 'road_list/index'

  post 'road_list/new'

  get 'road_list/delete'

  get 'road_list/print'

  get 'road_list/download'

  

 

  root 'sessions#new'
  delete 'stations/:id' => 'stations#destroy', as: 'delstation'
  get 'stations' => 'stations#new', as: 'newstation'
  get 'stations/index' => 'stations#index', as: 'stationsindex'
  post 'stations' => 'stations#create', as: 'createstation'
  get 'reports' => 'reports#index', as: 'reportindex'
  get 'reports/new' => 'reports#new', as: 'reportnew'
  post 'reports' => 'reports#create', as: 'savereport'
  get 'reports/show' => 'reports#show', as: 'showreport'
  get 'reports/edit' => 'reports#edit', as: 'editreport'
  get 'reports/search' => 'reports#search', as:'reportsearch'
  get 'reports/choiceedit' => 'reports#choiceedit', as:'choiceedit'
  get 'reports' => 'reports#update', as:'updatereport'
  delete 'reports/:id' => 'reports#destroy', as:'delreport'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'download' => 'reports#download'
  get 'print' => 'reports#print'
  

  resources :users
 

	

end

app/models/cartridge_transfer.rb
# == Schema Information
#
# Table name: cartridge_transfers
#
#  id         :integer          not null, primary key
#  model      :integer
#  count      :integer
#  date       :date
#  department :text
#  person_out :integer
#  person_in  :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CartridgeTransfer < ActiveRecord::Base
end

app/controllers/cartridge_transfers_controller.rb
class CartridgeTransfersController < ApplicationController
  before_action :set_cartridge_transfer, only: [:show, :edit, :update, :destroy]

  # GET /cartridge_transfers
  # GET /cartridge_transfers.json
  def index
    @cartridge_transfers = CartridgeTransfer.all
  end

  # GET /cartridge_transfers/1
  # GET /cartridge_transfers/1.json
  def show
  end

  # GET /cartridge_transfers/new
  def new
    @cartridge_transfer = CartridgeTransfer.new
  end

  # GET /cartridge_transfers/1/edit
  def edit
  end

  # POST /cartridge_transfers
  # POST /cartridge_transfers.json
  def create
    @cartridge_transfer = CartridgeTransfer.new(cartridge_transfer_params)

    respond_to do |format|
      if @cartridge_transfer.save
        format.html { redirect_to @cartridge_transfer, notice: 'Cartridge transfer was successfully created.' }
        format.json { render :show, status: :created, location: @cartridge_transfer }
      else
        format.html { render :new }
        format.json { render json: @cartridge_transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartridge_transfers/1
  # PATCH/PUT /cartridge_transfers/1.json
  def update
    respond_to do |format|
      if @cartridge_transfer.update(cartridge_transfer_params)
        format.html { redirect_to @cartridge_transfer, notice: 'Cartridge transfer was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartridge_transfer }
      else
        format.html { render :edit }
        format.json { render json: @cartridge_transfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartridge_transfers/1
  # DELETE /cartridge_transfers/1.json
  def destroy
    @cartridge_transfer.destroy
    respond_to do |format|
      format.html { redirect_to cartridge_transfers_url, notice: 'Cartridge transfer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartridge_transfer
      @cartridge_transfer = CartridgeTransfer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartridge_transfer_params
      params.require(:cartridge_transfer).permit(:model, :count, :date, :department, :person_out, :person_in)
    end
end

app/helpers/cartridge_transfers_helper.rb
module CartridgeTransfersHelper
end

app/views/cartridge_transfers/_form.html.erb
<%= form_for(@cartridge_transfer) do |f| %>
  <% if @cartridge_transfer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cartridge_transfer.errors.count, "error") %> prohibited this cartridge_transfer from being saved:</h2>

      <ul>
      <% @cartridge_transfer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.number_field :model %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_area :department %>
  </div>
  <div class="field">
    <%= f.label :person_out %><br>
    <%= f.number_field :person_out %>
  </div>
  <div class="field">
    <%= f.label :person_in %><br>
    <%= f.text_area :person_in %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cartridge_transfers/edit.html.erb
<h1>Editing Cartridge Transfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @cartridge_transfer %> |
<%= link_to 'Back', cartridge_transfers_path %>

app/views/cartridge_transfers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cartridge Transfers</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>Count</th>
      <th>Date</th>
      <th>Department</th>
      <th>Person out</th>
      <th>Person in</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartridge_transfers.each do |cartridge_transfer| %>
      <tr>
        <td><%= cartridge_transfer.model %></td>
        <td><%= cartridge_transfer.count %></td>
        <td><%= cartridge_transfer.date %></td>
        <td><%= cartridge_transfer.department %></td>
        <td><%= cartridge_transfer.person_out %></td>
        <td><%= cartridge_transfer.person_in %></td>
        <td><%= link_to 'Show', cartridge_transfer %></td>
        <td><%= link_to 'Edit', edit_cartridge_transfer_path(cartridge_transfer) %></td>
        <td><%= link_to 'Destroy', cartridge_transfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartridge transfer', new_cartridge_transfer_path %>

app/views/cartridge_transfers/new.html.erb
<h1>New Cartridge Transfer</h1>

<%= render 'form' %>

<%= link_to 'Back', cartridge_transfers_path %>

app/views/cartridge_transfers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @cartridge_transfer.model %>
</p>

<p>
  <strong>Count:</strong>
  <%= @cartridge_transfer.count %>
</p>

<p>
  <strong>Date:</strong>
  <%= @cartridge_transfer.date %>
</p>

<p>
  <strong>Department:</strong>
  <%= @cartridge_transfer.department %>
</p>

<p>
  <strong>Person out:</strong>
  <%= @cartridge_transfer.person_out %>
</p>

<p>
  <strong>Person in:</strong>
  <%= @cartridge_transfer.person_in %>
</p>

<%= link_to 'Edit', edit_cartridge_transfer_path(@cartridge_transfer) %> |
<%= link_to 'Back', cartridge_transfers_path %>