config/routes.rb
Rails.application.routes.draw do
  
  resources :cartridge_transfers
  resources :cartridge_supplies
  resources :cartridges
  get 'checklist/index'

  get 'checklist/new'

  resources :day_road_lists

  
  get 'road_list/index'

  post 'road_list/new'

  get 'road_list/delete'

  get 'road_list/print'

  get 'road_list/download'

  

 

  root 'sessions#new'
  delete 'stations/:id' => 'stations#destroy', as: 'delstation'
  get 'stations' => 'stations#new', as: 'newstation'
  get 'stations/index' => 'stations#index', as: 'stationsindex'
  post 'stations' => 'stations#create', as: 'createstation'
  get 'reports' => 'reports#index', as: 'reportindex'
  get 'reports/new' => 'reports#new', as: 'reportnew'
  post 'reports' => 'reports#create', as: 'savereport'
  get 'reports/show' => 'reports#show', as: 'showreport'
  get 'reports/edit' => 'reports#edit', as: 'editreport'
  get 'reports/search' => 'reports#search', as:'reportsearch'
  get 'reports/choiceedit' => 'reports#choiceedit', as:'choiceedit'
  get 'reports' => 'reports#update', as:'updatereport'
  delete 'reports/:id' => 'reports#destroy', as:'delreport'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'download' => 'reports#download'
  get 'print' => 'reports#print'
  

  resources :users
 

	

end

app/models/day_road_list.rb
# == Schema Information
#
# Table name: day_road_lists
#
#  id         :integer          not null, primary key
#  day        :date
#  fuel       :integer
#  station    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class DayRoadList < ActiveRecord::Base
end

app/controllers/day_road_lists_controller.rb
class DayRoadListsController < ApplicationController
  before_action :set_day_road_list, only: [:show, :edit, :update, :destroy]

  # GET /day_road_lists
  # GET /day_road_lists.json
  def index
  #  @day_road_lists = DayRoadList.all.sort_by(&:day)
   @day_road_lists = DayRoadList.all.order(day: :asc)
  end


  # GET /day_road_lists/1
  # GET /day_road_lists/1.json
  def show
    @stid = @day_road_listid.station
    @stname = Station.find(@stid)
    @stn = @stname.name
  end

  # GET /day_road_lists/new
  def new
    @day_road_list = DayRoadList.new
  end

  # GET /day_road_lists/1/edit
  def edit
  end

  # POST /day_road_lists
  # POST /day_road_lists.json
  def create
    
    @day_road_list = DayRoadList.new(day_road_list_params)

    respond_to do |format|
      if @day_road_list.save
        format.html { redirect_to @day_road_list, notice: 'Данные добавлены' }
        format.json { render :index,  location: @day_road_list }
      else
        format.html { render :new }
        format.json { render json: @day_road_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /day_road_lists/1
  # PATCH/PUT /day_road_lists/1.json
  def update
    respond_to do |format|
      if @day_road_list.update(day_road_list_params)
        format.html { redirect_to @day_road_list, notice: 'Day road list was successfully updated.' }
        format.json { render :show, status: :ok, location: @day_road_list }
      else
        format.html { render :edit }
        format.json { render json: @day_road_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /day_road_lists/1
  # DELETE /day_road_lists/1.json
  def destroy
    @day_road_listing.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to day_road_lists_url, notice: 'Day road list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_day_road_list
      @day_road_listid = DayRoadList.find(params[:id])
      @day_road_listing = DayRoadList.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_road_list_params
      params.require(:day_road_list).permit(:day, :fuel, :station)
    end
end

app/helpers/day_road_lists_helper.rb
module DayRoadListsHelper
end

app/views/day_road_lists/_form.html.erb
<%= form_for(@day_road_list) do |f| %>
  <% if @day_road_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@day_road_list.errors.count, "error") %> prohibited this day_road_list from being saved:</h2>

      <ul>
      <% @day_road_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'ДЕНЬ' %><br>
    <%= f.date_select :day %> 
    </div>

  <div class="field">
    <%= f.label 'ОБЬЕМ' %><br>
    <%= f.number_field :fuel %>
  </div>
  <div class="field">
    <%= f.label 'АЗС' %><br>
    <%= f.select :station, options_from_collection_for_select(Station.all, :id, :name), prompt: "Выберите АЗС" %>

  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/day_road_lists/edit.html.erb
<h1>Editing Day Road List</h1>


<%= link_to 'Show', @day_road_list %> |
<%= link_to 'Back', day_road_lists_path %>

app/views/day_road_lists/index.html.erb
<!--<p id="notice"><%= notice %></p> -->

<h1>Список поданных данных index</h1>

<table border="3", align="top", cellpadding="30", cellspacing="10">
  <thead>
    <tr>
      <th>Day</th>
      <th>Fuel</th>
      <th>Station</th>
      <th colspan="3">Удалить</th>
    </tr>
  </thead>

  <tbody>
    <% @day_road_lists.each do |day_road_list| %>
      <tr>
        <td><%= day_road_list.day %></td>
        <td><%= day_road_list.fuel %></td>
        <td><%= (Station.find(day_road_list.station)).name %></td>
        <td><%= link_to 'Show', day_road_list %></td>
        <td><%= link_to 'Edit', edit_day_road_list_path(day_road_list) %></td>
        <td><%= link_to 'Destroy', day_road_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<h3><%= link_to 'Добаить новое значение', new_day_road_list_path %></h3>

app/views/day_road_lists/new.html.erb
<h1>New Day Road List</h1>

<%= render 'form' %>

<%= link_to 'Back', day_road_lists_path %>

app/views/day_road_lists/show.html.erb
<h1>Список поданных данных ishow</h1>

<table border="3", align="top", cellpadding="30", cellspacing="10">
<tbody>
  <thead>
    <tr>
      <th>------День-------</th>
      <th>------Fuel-------</th>
      <th>------Station----</th>
      <th>------Удалить----</th>
    </tr>  
  </thead>
    <tr>
      <td><%=@day_road_listid.day %></td>
      <td><%= @day_road_listid.fuel %></td>
      <td><%= @stn %></td>
      <td><%= link_to 'Удалить', day_road_list_path, method: :delete, data: { confirm: 'Вы уверены что хотите удалить запись?' } %></td>
    </tr>
  </tbody>
  </table>
<h3><%= link_to 'Добаить новое значение', new_day_road_list_path %></h3>