config/routes.rb
Rails.application.routes.draw do
  
  resources :cartridge_transfers
  resources :cartridge_supplies
  resources :cartridges
  get 'checklist/index'

  get 'checklist/new'

  resources :day_road_lists

  
  get 'road_list/index'

  post 'road_list/new'

  get 'road_list/delete'

  get 'road_list/print'

  get 'road_list/download'

  

 

  root 'sessions#new'
  delete 'stations/:id' => 'stations#destroy', as: 'delstation'
  get 'stations' => 'stations#new', as: 'newstation'
  get 'stations/index' => 'stations#index', as: 'stationsindex'
  post 'stations' => 'stations#create', as: 'createstation'
  get 'reports' => 'reports#index', as: 'reportindex'
  get 'reports/new' => 'reports#new', as: 'reportnew'
  post 'reports' => 'reports#create', as: 'savereport'
  get 'reports/show' => 'reports#show', as: 'showreport'
  get 'reports/edit' => 'reports#edit', as: 'editreport'
  get 'reports/search' => 'reports#search', as:'reportsearch'
  get 'reports/choiceedit' => 'reports#choiceedit', as:'choiceedit'
  get 'reports' => 'reports#update', as:'updatereport'
  delete 'reports/:id' => 'reports#destroy', as:'delreport'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'logout' => 'sessions#destroy'
  get 'download' => 'reports#download'
  get 'print' => 'reports#print'
  

  resources :users
 

	

end

app/models/report.rb
# == Schema Information
#
# Table name: reports
#
#  id                 :integer          not null, primary key
#  station            :integer
#  f95                :integer
#  f92                :integer
#  f80                :integer
#  fdt                :integer
#  fgaz               :integer
#  magazine           :integer
#  vipcardonstock     :integer
#  vipcardtreid       :integer
#  discountonstock    :integer
#  discounttreid      :integer
#  carwasher          :integer
#  allinstation       :integer
#  allf95             :integer
#  allf92             :integer
#  allf80             :integer
#  allfdt             :integer
#  allfgaz            :integer
#  allmagazine        :integer
#  allvipcardonstock  :integer
#  allvipcardtreid    :integer
#  alldiscountonstock :integer
#  alldiscounttreid   :integer
#  allcarwasher       :integer
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  changetime         :date
#  deleted_at         :datetime
#

class Report < ActiveRecord::Base
	acts_as_paranoid
	validates :f95, numericality: { only_integer: true }
	validates :f92, numericality: { only_integer: true }
	validates :f80, numericality: { only_integer: true }
	validates :fdt, numericality: { only_integer: true }
	validates :fgaz, numericality: { only_integer: true }
	validates :magazine, numericality: { only_integer: true }
	validates :vipcardonstock, numericality: { only_integer: true }
	validates :vipcardtreid, numericality: { only_integer: true }
	validates :discountonstock, numericality: { only_integer: true }
	validates :discounttreid, numericality: { only_integer: true }
	validates :carwasher, numericality: { only_integer: true }
	validates :allinstation, numericality: { only_integer: true }
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  def index
	@reports = Report.all
  end

  def show
  end

  def edit
  end

  def create
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def index
	@reports = Report.all
  @stats
  @stat = 0
  
  end
  def new
    @station=Station.all
  	@report = Report.new

  	
  end

  def show
    
  end

  def edit
    @repforedit = Report.where(changetime: params[:time], station: params[:station])
  end

  def search
    @repdate= Report.where(changetime: params[:time])
    @checkdate = (params[:time]).to_date

    @all95 = @repdate.map(&:f95).inject(&:+) 
    @all92 = @repdate.map(&:f92).inject(&:+)
    @all80 = @repdate.map(&:f80).inject(&:+)
    @alldt = @repdate.map(&:fdt).inject(&:+)
    @allfuel = @repdate.map(&:allinstation).inject(&:+)
    @allgaz = @repdate.map(&:fgaz).inject(&:+)
    @allmagazine = @repdate.map(&:magazine).inject(&:+)


      
    
      
    
  end

  def choiceedit
  end

  def update
  end

  def create
    @station = Station.all
    @sts = @stats

  	@report = Report.new(master_params)
      if @report.save
        #sesion[:user_id] = @user.id
        render "ok"
      else
        render "users/err"
      end
  end

  def destroy
    @delreport = Report.find(params[:id])
    @delreport.destroy
    redirect_to reportnew_path
  end

  def info
  end

  def print
    @repdate= Report.where(changetime: params[:time])
    @checkdate = (params[:time]).to_date

    @all95 = @repdate.map(&:f95).inject(&:+) 
    @all92 = @repdate.map(&:f92).inject(&:+)
    @all80 = @repdate.map(&:f80).inject(&:+)
    @alldt = @repdate.map(&:fdt).inject(&:+)
    @allfuel = @repdate.map(&:allinstation).inject(&:+)
    @allgaz = @repdate.map(&:fgaz).inject(&:+)
    @allmagazine = @repdate.map(&:magazine).inject(&:+)


    render  'reports/print', layout: false
  end



  private
  def master_params
    params.require(:report).permit(
      :station, 
      :f95, 
      :f92,         
      :f80,              
      :fdt,              
      :fgaz,               
      :magazine, 
      :vipcardonstock,     
      :vipcardtreid,  
      :discountonstock,    
      :discounttreid,      
      :carwasher,  
      :allinstation, 
      :changetime)
  end 
  
  
end

app/helpers/report_helper.rb
module ReportHelper
end

app/views/reports/choiceedit.html.erb
<h1>Выберите дату и обьект для исправления данных отчета</h1>


<%= form_tag("/reports/edit", method: "get") do %>
  <%= select_tag :time,options_for_select([Date.current, Date.current - 1,Date.current - 2, Date.current - 3,Date.current - 4]), prompt: "Выберите дату" %> <br><br>
  <%= select_tag :station, options_from_collection_for_select(Station.all, :id, :name), prompt: "Выберите АЗС" %>
  <br>
  <br>
  
  <%= submit_tag("Найти и исправить") %>
<% end %>

app/views/reports/create.html.erb
<h1>Report#create</h1>
<p>Find me in app/views/report/create.html.erb</p>

app/views/reports/edit.html.erb
<h1><font color="#2A6496">Отчет по реализации    <h3><%= params[:time]  %></h3></font></h1>











<table class="test" width="200" cellpadding="20" cellspacing="40" border="0">
	<tr style="border-bottom: 3px solid #808080;">	
		<th>Наименоание Азс</th>	
		<th>Аи95</th>	
		<th>Аи92</th>	
		<th>А80</th>	
		<th>Дт</th>	
		<th>Итого топлива</th>
		<th>Газ</th>
		<th>Магазин выручка</th>
		<th>Вип карт на складе</th>
		<th>Вип карт продано</th>
		<th>Дисконтных карт на складе</th>	
		<th>Дисконтных карт продано</th>	
		<th>Мойка выручка</th>	
	</tr>
<% @repforedit.each do |t| %>

	<tr>	
	<% @stname = Station.find_by id:t.station %>
		<td width="150px" align="left" valign="top"><%= @stname.name %></td>	
		<td width="150px" align="left" valign="top"><%= t.f95 %></td>	
		<td width="150px" align="left" valign="top"><%= t.f92 %></td> 
		<td width="150px" align="left" valign="top"><%= t.f80 %></td> 
		<td width="150px" align="left" valign="top"><%= t.fdt %></td> 
		<td width="150px" align="left" valign="top"><%= t.allinstation %></td> 
		<td width="150px" align="left" valign="top"><%= t.fgaz %></td> 
		<td width="150px" align="left" valign="top"><%= t.magazine %></td> 
		<td width="150px" align="left" valign="top"><%= t.vipcardonstock %></td> 
		<td width="150px" align="left" valign="top"><%= t.vipcardtreid %></td> 
		<td width="150px" align="left" valign="top"><%= t.discountonstock %></td> 
		<td width="150px" align="left" valign="top"><%= t.discounttreid %></td> 
		<td width="150px" align="left" valign="top"><%= t.carwasher %></td> 
		<td><%= link_to "Удалить и внести заново", delreport_path(t), method: :delete, data: {confirm: "Вы уверены?"}  %>
		<% @timeforheader = t.changetime %>
	</tr>

<% end %>
</table>

app/views/reports/index.html.erb
<h1></h1>
<h3>Данные вводить внимательно, не совершая ошибок!!! </h3>




 <h1><%= link_to "Внести данные", reportnew_path() %></h1>
    

app/views/reports/info.html.erb
<div class="welcome">
<ul>
<li><%= link_to "Ввод суточных данных АЗС", reportindex_path  %><br></li>
<li><%=link_to "Исправить неверно внесенные данные", choiceedit_path %><br></li>
<li><%= link_to "Сформировать суточный отчет", showreport_path  %> <br></li>
<li><%= link_to "Управление АЗС", :controller => "stations", :action => "index" %></li>
<li><%= link_to "Заправочные данные", :controller => "day_road_lists", :action => "index" %></li>
<li><%= link_to "CHECKLIST", :controller => "checklist", :action => "index" %></li>
</ul>
</div>

app/views/reports/new.html.erb
<h1>Ввод суточных данных</h1>
<p>Введите данные </p>




 <%= form_for :report, url: '/reports' do |f| %>
      <%= f.select :station, options_from_collection_for_select(Station.all, :id, :name), prompt: "Выберите АЗС" %><br><br>

      <%= f.select :changetime, options_for_select([Date.current, Date.current - 1,Date.current - 2, Date.current - 3,Date.current - 4]), prompt: "Выберите дату" %> <br><br>
      <%= f.text_field :f95, :placeholder => 'Аи 95' %>
      <%= f.text_field :f92, :placeholder => 'Аи 92' %>
      <%= f.text_field :f80, :placeholder => 'А 80' %>
      <%= f.text_field :fdt, :placeholder => 'Дизельное топливо' %>
      <%= f.text_field :fgaz, :placeholder => 'ГАЗ' %>
      <%= f.text_field :magazine, :placeholder => 'Выручка магазина' %>
      <%= f.text_field :vipcardonstock, :placeholder => 'Вип карты на складе' %>
      <%= f.text_field :vipcardtreid, :placeholder => 'Продано ВИП карт' %>
      <%= f.text_field :discountonstock, :placeholder => 'Дисконтные карты на складе' %>
      <%= f.text_field :discounttreid, :placeholder => 'Продано Дисконтных карт' %>
      <%= f.text_field :carwasher, :placeholder => 'Мойка - выручка' %>
      <%= f.text_field :allinstation, :placeholder => 'Общее количество топлива' %><br><br>
      <%= f.submit "Внести данные", :class => "form-btn" %>
            
    <% end %>

app/views/reports/ok.html.erb
<h1> Данные внесены! </h1>
<h3><%=link_to "Внести данные для другой АЗС?", reportnew_path %>
<br>
<br>
<br>
<h3><%= link_to "Исправить неверно внесенные данные?", choiceedit_path %></h3>

app/views/reports/print.html.erb
<title>Коп Автодорстрой</title>

<h1><font color="#2A6496">Отчет по реализации на объектах КОП "Автодорстрой" за  <h3><%= (@checkdate - 1)  %></h3></font></h1>











<table class="test" width="200" cellpadding="20" cellspacing="40" border="0">
	<tr style="border-bottom: 3px solid #808080;">	
		<th>Наименоание Азс</th>	
		<th>Аи95</th>	
		<th>Аи92</th>	
		<th>А80</th>	
		<th>Дт</th>	
		<th>Итого топлива</th>
		<th>Газ</th>
		<th>Магазин выручка</th>
		<th>Вип карт на складе</th>
		<th>Вип карт продано</th>
		<th>Дисконтных карт на складе</th>	
		<th>Дисконтных карт продано</th>	
		<th>Мойка выручка</th>	
	</tr>
<% @repdate.each do |t| %>

	<tr>	
	<% @stname = Station.find_by id:t.station %>
		<td width="150px" align="left" valign="top"><%= @stname.name %></td>	
		<td width="150px" align="left" valign="top"><%= t.f95 %></td>	
		<td width="150px" align="left" valign="top"><%= t.f92 %></td> 
		<td width="150px" align="left" valign="top"><%= t.f80 %></td> 
		<td width="150px" align="left" valign="top"><%= t.fdt %></td> 
		<td width="150px" align="left" valign="top"><%= t.allinstation %></td> 
		<td width="150px" align="left" valign="top"><%= t.fgaz %></td> 
		<td width="150px" align="left" valign="top"><%= t.magazine %></td> 
		<td width="150px" align="left" valign="top"><%= t.vipcardonstock %></td> 
		<td width="150px" align="left" valign="top"><%= t.vipcardtreid %></td> 
		<td width="150px" align="left" valign="top"><%= t.discountonstock %></td> 
		<td width="150px" align="left" valign="top"><%= t.discounttreid %></td> 
		<td width="150px" align="left" valign="top"><%= t.carwasher %></td> 
		
	</tr>

<% end %>
<tr>
<td width="150px" align="left" valign="top">Итого</td>
<td width="150px" align="left" valign="top"><%= @all95 %></td>
<td width="150px" align="left" valign="top"><%= @all92 %></td>
<td width="150px" align="left" valign="top"><%= @all80 %></td>
<td width="150px" align="left" valign="top"><%= @alldt %></td>
<td width="150px" align="left" valign="top"><%= @allfuel %></td>
<td width="150px" align="left" valign="top"><%= @allgaz %></td>
<td width="150px" align="left" valign="top"><%= @allmagazine %></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>

</tr>
	


</table>

app/views/reports/search.html.erb
<h1><font color="#2A6496">Отчет по реализации  за  <h3><%= @checkdate - 1  %></h3></font></h1>











<table class="test" width="200" cellpadding="20" cellspacing="40" border="0">
	<tr style="border-bottom: 3px solid #808080;">	
		<th>Наименование Азс</th>	
		<th>Аи95</th>	
		<th>Аи92</th>	
		<th>А80</th>	
		<th>Дт</th>	
		<th>Итого топлива</th>
		<th>Газ</th>
		<th>Магазин выручка</th>
		<th>Вип карт на складе</th>
		<th>Вип карт продано</th>
		<th>Дисконтных карт на складе</th>	
		<th>Дисконтных карт продано</th>	
		<th>Мойка выручка</th>	
	</tr>
<% @repdate.each do |t| %>

	<tr>	
	<% @stname = Station.find_by id:t.station %>
		<td width="150px" align="left" valign="top"><%= @stname.name %></td>	
		<td width="150px" align="left" valign="top"><%= t.f95 %></td>	
		<td width="150px" align="left" valign="top"><%= t.f92 %></td> 
		<td width="150px" align="left" valign="top"><%= t.f80 %></td> 
		<td width="150px" align="left" valign="top"><%= t.fdt %></td> 
		<td width="150px" align="left" valign="top"><%= t.allinstation %></td> 
		<td width="150px" align="left" valign="top"><%= t.fgaz %></td> 
		<td width="150px" align="left" valign="top"><%= t.magazine %></td> 
		<td width="150px" align="left" valign="top"><%= t.vipcardonstock %></td> 
		<td width="150px" align="left" valign="top"><%= t.vipcardtreid %></td> 
		<td width="150px" align="left" valign="top"><%= t.discountonstock %></td> 
		<td width="150px" align="left" valign="top"><%= t.discounttreid %></td> 
		<td width="150px" align="left" valign="top"><%= t.carwasher %></td> 
		
	</tr>

<% end %>
<tr>
<td width="150px" align="left" valign="top">Итого</td>
<td width="150px" align="left" valign="top"><%= @all95 %></td>
<td width="150px" align="left" valign="top"><%= @all92 %></td>
<td width="150px" align="left" valign="top"><%= @all80 %></td>
<td width="150px" align="left" valign="top"><%= @alldt %></td>
<td width="150px" align="left" valign="top"><%= @allfuel %></td>
<td width="150px" align="left" valign="top"><%= @allgaz %></td>
<td width="150px" align="left" valign="top"><%= @allmagazine %></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>
<td width="150px" align="left" valign="top"><***></td>

</tr>
	


</table>

<h2><%= link_to "Версия для печати", :controller => "reports", :action => "print", :time => @checkdate %></h2>

app/views/reports/show.html.erb
<h1>Отчет по реализации АЗС КОП "АВТОДОРСТРОЙ"</h1>
<br><br>
<br><br>
<br><br>
<h3> Выберите дату </h3>

<%= form_tag("/reports/search", method: "get") do %>
  <%= select_tag :time,options_for_select([Date.current, Date.today - 1,Date.today - 2, Date.today - 3,Date.today - 4]), prompt: "Выберите дату" %> <br><br>
  
  <%= submit_tag("Показать") %>
<% end %>